language: ruby
rvm:
  - 2.1
  - 2.2
  - 2.3.3
  - 2.4.0
addons:
  firefox: 51.0
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - gem update --system
  - gem --version
  - gem install bundler rake
script: rake commit
cache: bundler
notifications:
  email:
    on_success: change
    on_failure: always
