language: ruby
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - 2.3.1
addons:
  firefox: latest
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - gem install bundler
cache: bundler
notifications:
  email:
    on_success: change
    on_failure: always
